local name_m_work0y 		"Mother works, birth"
local name_m_work1y6m 		"Mother works, 1.5 years"
local name_m_work2y6m 		"Mother works, 2.5 years"
local name_m_work3y6m 		"Mother works, 3.5 years"
local name_m_work4y6m		"Mother works, 4.5 years"
local name_mb_ed1y6m 		"Biol. Mother's ed., 1.5 years"		
local name_mb_ed2y6m 		"Biol. Mother's ed., 2.5 years"	
local name_mb_ed3y6m 		"Biol. Mother's ed., 3.5 years"	
local name_mb_ed4y6m 		"Biol. Mother's ed., 4.5 years"	
local name_mb_ed8y	 		"Biol. Mother's ed., 8 years"
local name_m_ed0y 			"Mother's ed., 0 years"	
local name_m_ed1y6m 		"Mother's ed., 1.5 years"	
local name_m_ed2y6m 		"Mother's ed., 2.5 years"	
local name_m_ed3y6m 		"Mother's ed., 3.5 years"	
local name_m_ed4y6m 		"Mother's ed., 4.5 years"	
local name_m_ed5y6m 		"Mother's ed., 5.5 years"
local name_m_ed8y	 		"Mother's ed., 8 years"	
local name_m_ed12y			"Mother's ed., 12 years"
local name_m_ed15y 			"Mother's ed., 15 years"

local name_f_home1y6m 		"Father at home, 1.5 years"
local name_f_home8y    		"Father at home, 8 years"

local name_hh_inc12y 		"Household income, 12 years"
local name_hh_inc15y		"Household income, 15 years"

local name_hh_sibs1y6m 		"Siblings, 1.5 years"
local name_hh_sibs8y		"Siblings, 8 years"

local name_home8y 		"HOME, 8 years"
local name_home4y6m 		"HOME, 4.5 years"
local name_home2y6m 		"HOME, 2.5 years"
local name_home1y6m 		"HOME, 1.5 years"
local name_home3y6m		"HOME, 3.5 years"
local name_home1y 		"HOME, 1 year"
local name_home0y6m		"HOME, 0.5 years"

local name_home_abspun0y6m 		"HOME, Abs. Punish, 0.5 years" 
local name_home_abspun1y6m 		"HOME, Abs. Punish, 1.5 years" 
local name_home_abspun2y6m 		"HOME, Abs. Punish, 2.5 years" 
local name_home_abspun3y6m 		"HOME, Abs. Punish, 3.5 years"
local name_home_abspun4y6m 		"HOME, Abs. Punish, 4.5 years" 
local name_home_minvol0y6m 		"HOME, Mom Involve, 0.5 years" 
local name_home_minvol1y6m 		"HOME, Mom Involve, 1.5 years" 
local name_home_minvol2y6m 		"HOME, Mom Involve, 2.5 years"
local name_home_affect0y6m 		"HOME, Mom Warmth, 0.5 years"
local name_home_affect1y6m 		"HOME, Mom Warmth, 1.5 years" 
local name_home_affect2y6m 		"HOME, Mom Warmth, 2.5 years" 
local name_home_affect3y6m 		"HOME, Mom Warmth, 3.5 years"
local name_home_affect4y6m 		"HOME, Mom Warmth, 4.5 years" 
local name_home_orgenv0y6m 		"HOME, Organization of Env., 0.5 years"
local name_home_orgenv1y6m 		"HOME, Organization of Env., 1.5 years" 
local name_home_orgenv2y6m 		"HOME, Organization of Env., 2.5 years" 
local name_home_oppvar0y6m 		"HOME, Variety, 0.5 years" 
local name_home_oppvar1y6m 		"HOME, Variety, 1.5 years" 
local name_home_oppvar2y6m 		"HOME, Variety, 2.5 years"
local name_home_exper3y6m 		"HOME, Equip, Toys, Exp., 3.5 years"
local name_home_exper4y6m 		"HOME, Equip, Toys, Exp., 4.5 years"
local name_home_mature3y6m 		"HOME, Stim. of Mature Behavior, 3.5 years"
local name_home_mature4y6m 		"HOME, Stim. of Mature Behavior, 4.5 years"
local name_home_phyenv3y6m 		"HOME, Physical Env., 3.5 years"
local name_home_phyenv4y6m 		"HOME, Physical Env., 4.5 years"
local name_home_masc3y6m 		"HOME, Masculine Stimulation, 3.5 years"
local name_home_masc4y6m 		"HOME, Masculine Stimulation, 4.5 years"
local name_home_indep3y6m		"HOME, Independent from Parent, 3.5 years"
local name_home_indep4y6m		"HOME, Independent from Parent, 4.5 years"
local name_home_toys0y6m 		"HOME, Toys, 0.5 years"
local name_home_toys1y6m  		"HOME, Toys, 1.5 years"
local name_home_toys2y6m  		"HOME, Toys, 2.5 years"
local name_home_oppvar8y  		"HOME, Variety, 8 years"
local name_home_devstm8y  		"HOME, Develop. Stimulation, 8 years"
local name_home_emotin8y  		"HOME, Emotional Climate, 8 years"
local name_home_indep8y  		"HOME, Foster Indep, 8 years"
local name_home_leng8y  		"HOME, Language Env., 8 years"
local name_home_absrst8y  		"HOME, Need Gratify of Restriction, 8 years"
local name_home_orgenv8y  		"HOME, Organization of Env., 8 years"
local name_home_phyenv8y  		"HOME, Physical Env., 8 years"
local name_home_toys8y 			"HOME, Toys, 8 years"

local name_earlyhome 		"Early HOME, total"
local name_laterhome 		"School-age HOME, total"
local name_earlyhomeabs 	"Early HOME, no punish."
local name_laterhomeabs 	"School-age HOME, no punish."
local name_earlyhomephy 	"Early HOME, phy. env."
local name_laterhomephy 	"School-age HOME, phy. env."
local name_earlyhomemom 	"Early HOME, mother"
local name_laterhomemom 	"School-age HOME, mother"

local name_new_pari_auth0y6m 	"PARI, Authority, 0.5 years"
local name_new_pari_hostl0y6m 	"PARI, Hostility, 0.5 years"
local name_new_pari_demo0y6m	"PARI, Democratic, 0.5 years"
local name_new_pari_auth1y6m 	"PARI, Authority, 1.5 years"
local name_new_pari_hostl1y6m 	"PARI, Hostility, 1.5 years"
local name_new_pari_demo1y6m	"PARI, Democratic, 1.5 years"

local name_mdi1y 			"IQ, 1 year"
local name_iq2y 			"IQ, 2 years"
local name_iq3y 			"IQ, 3 years"
local name_iq3y6m 			"IQ, 3.5 years"
local name_iq4y 			"IQ, 4 years"
local name_iq4y6m 			"IQ, 4.5 years"
local name_iq5y				"IQ, 5 years"
local name_iq6y 			"IQ, 6 years"
local name_iq6y6m 			"IQ, 6.5 years"
local name_iq7y				"IQ, 7 years"
local name_iq8y				"IQ, 8 years"
local name_iq12y 			"IQ, 12 years"
local name_iq15y 			"IQ, 15 years"
local name_iq21y			"IQ, 21 years"

local name_vrb2y 			"Verbal IQ, 2 years"
local name_vrb3y 			"Verbal IQ, 3 years"
local name_vrb3y6m 			"Verbal IQ, 3.5 years"
local name_vrb4y 			"Verbal IQ, 4 years"
local name_vrb4y6m 			"Verbal IQ, 4.5 years"
local name_vrb5y			"Verbal IQ, 5 years"
local name_vrb6y			"Verbal IQ, 6 years"
local name_vrb6y6m			"Verbal IQ, 6.5 years"
local name_vrb7y			"Verbal IQ, 7 years"
local name_vrb8y			"Verbal IQ, 8 years"
local name_vrb12y 			"Verbal IQ, 12 years"
local name_vrb15y 			"Verbal IQ, 15 years"
local name_vrb21y			"Verbal IQ, 21 years"

local name_prf2y 			"Perf. IQ, 2 years"
local name_prf3y 			"Perf. IQ, 3 years"
local name_prf3y6m 			"Perf. IQ, 3.5 years"
local name_prf4y 			"Perf. IQ, 4 years"
local name_prf4y6m 			"Perf. IQ, 4.5 years"
local name_prf5y			"Perf. IQ, 5 years"
local name_prf6y			"Perf. IQ, 6 years"
local name_prf6y6m			"Perf. IQ, 6.5 years"
local name_prf7y			"Perf. IQ, 7 years"
local name_prf8y			"Perf. IQ, 8 years"
local name_prf12y 			"Perf. IQ, 12 years"
local name_prf15y 			"Perf. IQ, 15 years"
local name_prf21y			"Perf. IQ, 21 years"

local name_wis_vrb12y 			"WIS, Verbal IQ, 12 years"
local name_wis_prf12y			"WIS, Perf IQ, 12 years"

local name_cog				"School-age IQ, verbal"
local name_earlycog			"Early IQ, verbal"

local name_read5y6m 			"Achievement, Reading, 5.5 years"
local name_read6y  			"Achievement, Reading, 6 years"
local name_read6y6m  			"Achievement, Reading, 6.5 years"
local name_read7y  			"Achievement, Reading, 7 years"
local name_read7y6m 			"Achievement, Reading, 7.5 years" 
local name_read8y  			"Achievement, Reading, 8 years"
local name_read8y6m  			"Achievement, Reading, 8.5 years"
local name_read9y  			"Achievement, Reading, 9 years"
local name_read12y  			"Achievement, Reading, 12 years"
local name_read15y  			"Achievement, Reading, 15 years"
local name_read21y			"Achievement, Reading, 21 years"
local name_math5y6m  			"Achievement, Math, 5.5 years"
local name_math6y   			"Achievement, Math, 6 years"
local name_math6y6m   			"Achievement, Math, 6.5 years"
local name_math7y   			"Achievement, Math, 7 years"
local name_math7y6m  			"Achievement, Math, 7.5 years" 
local name_math8y   			"Achievement, Math, 8 years"
local name_math8y6m   			"Achievement, Math, 8.5 years"
local name_math9y   			"Achievement, Math, 9 years"
local name_math12y  			"Achievement, Math, 12 years"
local name_math15y  			"Achievement, Math, 15 years"
local name_math21y			"Achievement, Math, 21 years"
local name_know5y6m				"Achievement, Knowledge, 5.5 years"
local name_know6y				"Achievement, Knowledge, 6 years"
local name_know7y6m				"Achievement, Knowledge, 7.5 years"
local name_know8y				"Achievement, Knowledge, 8 years"
local name_know8y6m				"Achievement, Knowledge, 8.5 years"
local name_know9y				"Achievement, Knowledge, 9 years"
local name_know12y				"Achievement, Knowledge, 12 years"
local name_know21y				"Achievement, Knowledge, 21 years"
local name_ach5y6m   			"Achievement, Total, 5.5 years"
local name_ach6y    			"Achievement, Total, 6 years"
local name_ach7y6m    			"Achievement, Total, 7.5 years"
local name_ach8y    			"Achievement, Total, 8 years"
local name_ach8y6m    			"Achievement, Total, 8.5 years"
local name_ach9y    			"Achievement, Total, 9 years"
local name_ach12y   			"Achievement, Total, 12 years"
local name_ach21y			"Achievement, Total, 21 years"

* ---------------------------------------------------------------------------- *
* Non-cognitive
* ---------------------------------------------------------------------------- *

local name_ibr_sociab0y3m		"IBR, Sociability, 0.25 years"
local name_ibr_sociab0y6m		"IBR, Sociability, 0.5 years"
local name_ibr_sociab0y9m		"IBR, Sociability, 0.75 years"
local name_ibr_sociab1y			"IBR, Sociability, 1 year"
local name_ibr_sociab1y6m		"IBR, Sociability, 1.5 years"
local name_ibr_sociab2y			"IBR, Sociability, 2 years"
local name_ibr_actv0y3m		"IBR, Activity lvl., 0.25 years"
local name_ibr_actv0y6m		"IBR, Activity lvl., 0.5 years"
local name_ibr_actv0y9m		"IBR, Activity lvl., 0.75 years"
local name_ibr_actv1y			"IBR, Activity lvl., 1 year"
local name_ibr_actv1y6m		"IBR, Activity lvl., 1.5 years"
local name_ibr_actv2y			"IBR, Activity lvl., 2 years"
local name_ibr_task0y3m			"IBR, Task orient., 0.25 years"
local name_ibr_task0y6m			"IBR, Task orient., 0.5 years"
local name_ibr_task0y9m			"IBR, Task orient., 0.75 years"
local name_ibr_task1y			"IBR, Task orient., 1 year"
local name_ibr_task1y6m			"IBR, Task orient., 1.5 years"
local name_ibr_task2y			"IBR, Task orient., 2 years"
local name_ibr_coop0y6m			"IBR, Cooperativeness, 0.5 years"
local name_ibr_coop1y			"IBR, Cooperativeness, 1 year"
local name_ibr_coop1y6m			"IBR, Cooperativeness, 1.5 years"
local name_ibr_coop2y			"IBR, Cooperativeness, 2 years"

local name_new_cbi_ho5y6m 		"CBI, Agreeableness, 5.5 years"
local name_new_cbi_iv5y6m 		"CBI, Extraversion (rev.), 5.5 years"
local name_new_cbi_di5y6m 		"CBI, Task Orientation (rev.), 5.5 years"
local name_new_cbi_de5y6m 		"CBI, Independence, 5.5 years"
local name_cbi_ex5y6m 			"CBI, Extraversion, 5.5 years"
local name_cbi_cr5y6m 			"CBI, Creativity, 5.5 years"
local name_cbi_ve5y6m 			"CBI, Verbal Intelligence, 5.5 years"
local name_cbi_ta5y6m 			"CBI, Task Orientation, 5.5 years"
local name_cbi_co5y6m			"CBI, Considerate, 5.5 years"
local name_new_cbi_ho5y9m 		"CBI, Agreeableness, 5.75 years"
local name_new_cbi_iv5y9m 		"CBI, Extraversion (rev.), 5.75 years"
local name_new_cbi_di5y9m 		"CBI, Task Orientation (rev.), 5.75 years"
local name_new_cbi_de5y9m 		"CBI, Independence, 5.75 years"
local name_cbi_ex5y9m 			"CBI, Extraversion, 5.75 years"
local name_cbi_cr5y9m 			"CBI, Creativity, 5.75 years"
local name_cbi_ve5y9m 			"CBI, Verbal Intelligence, 5.75 years"
local name_cbi_ta5y9m 			"CBI, Task Orientation, 5.75 years"
local name_cbi_co5y9m			"CBI, Considerate, 5.75 years"
local name_new_cbi_ho6y 		"CBI, Agreeableness, 6 years"
local name_new_cbi_iv6y 		"CBI, Extraversion (rev.), 6 years"
local name_new_cbi_di6y		"CBI, Task Orientation (rev.), 6 years"
local name_new_cbi_de6y 		"CBI, Independence, 6 years"
local name_cbi_ex6y  			"CBI, Extraversion, 6 years"
local name_cbi_cr6y  			"CBI, Creativity, 6 years"
local name_cbi_ve6y  			"CBI, Verbal Intelligence, 6 years"
local name_cbi_ta6y  			"CBI, Task Orientation, 6 years"
local name_cbi_co6y 			"CBI, Considerate, 6 years"
local name_cbi_ex6y6m 			"CBI, Extraversion, 6.5 years"
local name_cbi_cr6y6m 			"CBI, Creativity, 6.5 years"
local name_cbi_ve6y6m 			"CBI, Verbal Intelligence, 6.5 years"
local name_cbi_ta6y6m 			"CBI, Task Orientation, 6.5 years"
local name_cbi_co6y6m			"CBI, Considerate, 6.5 years"
local name_new_cbi_ho6y6m 		"CBI, Agreeableness, 6.5 years"
local name_new_cbi_iv6y6m 		"CBI, Extraversion (rev.), 6.5 years"
local name_new_cbi_di6y6m		"CBI, Task Orientation (rev.), 6.5 years"
local name_new_cbi_de6y6m 		"CBI, Independence, 6.5 years"
local name_new_cbi_ho7y 		"CBI, Agreeableness, 7 years"
local name_new_cbi_iv7y 		"CBI, Extraversion (rev.), 7 years"
local name_new_cbi_di7y		"CBI, Task Orientation (rev.), 7 years"
local name_new_cbi_de7y 		"CBI, Independence, 7 years"
local name_cbi_ex7y  			"CBI, Extraversion, 7 years"
local name_cbi_cr7y  			"CBI, Creativity, 7 years"
local name_cbi_ve7y  			"CBI, Verbal Intelligence, 7 years"
local name_cbi_ta7y  			"CBI, Task Orientation, 7 years"
local name_cbi_co7y 			"CBI, Considerate, 7 years"
local name_cbi_ex7y6m 			"CBI, Extraversion, 7.5 years"
local name_cbi_cr7y6m 			"CBI, Creativity, 7.5 years"
local name_cbi_ve7y6m 			"CBI, Verbal Intelligence, 7.5 years"
local name_cbi_ta7y6m 			"CBI, Task Orientation, 7.5 years"
local name_cbi_co7y6m			"CBI, Considerate, 7.5 years"
local name_new_cbi_ho7y6m 		"CBI, Agreeableness, 7.5 years"
local name_new_cbi_iv7y6m 		"CBI, Extraversion (rev.), 7.5 years"
local name_new_cbi_di7y6m		"CBI, Task Orientation (rev.), 7.5 years"
local name_new_cbi_de7y6m 		"CBI, Independence, 7.5 years"
local name_new_cbi_ho8y 		"CBI, Agreeableness, 8 years"
local name_new_cbi_iv8y 		"CBI, Extraversion (rev.), 8 years"
local name_new_cbi_di8y		"CBI, Task Orientation (rev.), 8 years"
local name_new_cbi_de8y 		"CBI, Independence, 8 years"
local name_cbi_ex8y  			"CBI, Extraversion, 8 years"
local name_cbi_cr8y  			"CBI, Creativity, 8 years"
local name_cbi_ve8y  			"CBI, Verbal Intelligence, 8 years"
local name_cbi_ta8y  			"CBI, Task Orientation, 8 years"
local name_cbi_co8y 			"CBI, Considerate, 8 years"
local name_new_cbi_ho12y		"CBI, Agreeableness, 12 years"
local name_new_cbi_de12y 		"CBI, Independence, 12 years"
local name_new_cbi_di12y 		"CBI, Task Orientation (rev.), 12 years"
local name_new_cbi_iv12y 		"CBI, Extraversion (rev.), 12 years"
local name_cbi_ex12y 			"CBI, Extraversion, 12 years"
local name_cbi_cr12y 			"CBI, Creativity, 12 years"
local name_cbi_ve12y 			"CBI, Verbal Intelligence, 12 years"
local name_cbi_ta12y 			"CBI, Task Orientation, 12 years"
local name_cbi_co12y			"CBI, Considerate, 12 years"
local name_new_wlkr_act8y 		"Walker, Well Behaved, 8 years"
local name_new_wlkr_withd8y 	"Walker, Extraversion, 8 years"
local name_new_wlkr_dst8y 		"Walker, Task Orientation, 8 years"
local name_new_wlkr_peer8y 		"Walker, Good Peer Relationships, 8 years"
local name_new_wlkr_immt8y		"Walker, Mature, 8 years"
local name_wlkr_tot				"Walker, Total Score, 8 years"
local name_new_kr_dst2y 		"KR, Attentive/Cooperative (rev.), 2 years" 
local name_kr_att2y 			"KR, Attentive/Cooperative, 2 years"
local name_new_kr_withd2y 		"KR, Confident/Friendly (rev.), 2 years"
local name_kr_conf2y			"KR, Confident/Friendly, 2 years"
local name_new_kr_dst2y6m 		"KR, Attentive/Cooperative (rev.), 2.5 years" 
local name_kr_att2y6m 			"KR, Attentive/Cooperative, 2.5 years"
local name_new_kr_withd2y6m 	"KR, Confident/Friendly (rev.), 2.5 years"
local name_kr_conf2y6m			"KR, Confident/Friendly, 2.5 years"
local name_new_kr_dst3y 		"KR, Attentive/Cooperative (rev.), 3 years" 
local name_kr_att3y 			"KR, Attentive/Cooperative, 3 years"
local name_new_kr_withd3y 		"KR, Confident/Friendly (rev.), 3 years"
local name_kr_conf3y			"KR, Confident/Friendly, 3 years"
local name_new_kr_dst4y 		"KR, Attentive/Cooperative (rev.), 4 years" 
local name_kr_att4y 			"KR, Attentive/Cooperative, 4 years"
local name_new_kr_withd4y 		"KR, Confident/Friendly (rev.), 4 years"
local name_kr_conf4y			"KR, Confident/Friendly, 4 years"
local name_new_kr_dst4y 		"KR, Attentive/Cooperative (rev.), 4 years" 
local name_kr_att4y 			"KR, Attentive/Cooperative, 4 years"
local name_new_kr_withd4y 		"KR, Confident/Friendly (rev.), 4 years"
local name_kr_conf4y			"KR, Confident/Friendly, 4 years"
local name_new_kr_dst5y 		"KR, Attentive/Cooperative (rev.), 5 years" 
local name_kr_att5y 			"KR, Attentive/Cooperative, 5 years"
local name_new_kr_withd5y 		"KR, Confident/Friendly (rev.), 5 years"
local name_kr_conf5y			"KR, Confident/Friendly, 5 years"
local name_new_kr_dst6y6m 		"KR, Attentive/Cooperative (rev.), 6y6m years" 
local name_kr_att6y6m 			"KR, Attentive/Cooperative, 6y6m years"
local name_new_kr_withd6y6m		"KR, Confident/Friendly (rev.), 6y6m years"
local name_kr_conf6y6m			"KR, Confident/Friendly, 6y6m years"
local name_new_kr_dst7y 		"KR, Attentive/Cooperative (rev.), 7 years" 
local name_kr_att7y 			"KR, Attentive/Cooperative, 7 years"
local name_new_kr_withd7y 		"KR, Confident/Friendly (rev.), 7 years"
local name_kr_conf7y			"KR, Confident/Friendly, 7 years"
local name_new_easy_gen 		"EASI, Less Emotionality, 8 years"
local name_new_easy_fear 		"EASI, Less Fear (rev.), (rev.) 8 years"
local name_new_easy_ang 		"EASI, Less Anger (rev.), 8 years"
local name_new_easy_temp 		"EASI, Less Tempo (rev.), 8 years"
local name_new_easy_vig 		"EASI, Less Vigor (rev.), 8 years"
local name_new_easy_cont 		"EASI, Control (rev.), 8 years"
local name_new_easy_deci 		"EASI, Decisive (rev.), 8 years"
local name_new_easy_sens 		"EASI, Less Sensation (rev.), 8 years"
local name_new_easy_pers 		"EASI, Persistence (rev.), 8 years"
local name_easy_soci			"EASI, Sociability (rev.), 8 years"

local name_earlyncog			"Early IBR, task orient."
local name_ncog			"School-age CBI, task orient."

local name_cat_readst8y 		"CAT, Reading, 8 years"
local name_cat_mathst8y		"CAT, Math, 8 years"
local name_wj_readas12y 		"WJ, Reading, 12 years"
local name_wj_mathas12y 		"WJ, Math, 12 years"
local name_wj_langas12y 		"WJ, Language, 12 years" 
local name_wj_knowas12y 		"WJ, Knowledge, 12 years" 
local name_wj_skillas12y 		"WJ, Skills, 12 years" 
local name_wj_readas5y6m 		"WJ, Reading, 5.5 years"
local name_wj_mathas5y6m 		"WJ, Math, 5.5 years" 
local name_wj_langas5y6m 		"WJ, Language, 5.5 years" 
local name_wj_knowas5y6m 		"WJ, Knowledge, 5.5 years" 
local name_wj_skillas5y6m 		"WJ, Skills, 5.5 years" 
local name_wj_readas6y 		"WJ, Reading, 6 years" 
local name_wj_mathas6y 		"WJ, Math, 6 years" 
local name_wj_langas6y 		"WJ, Language, 6 years"  
local name_wj_knowas6y 		"WJ, Knowledge, 6 years"  
local name_wj_skillas6y 		"WJ, Skills, 6 years"  
local name_wj_readas7y6m  		"WJ, Reading, 7.5 years" 
local name_wj_mathas7y6m  		"WJ, Math, 7.5 years"  
local name_wj_langas7y6m  		"WJ, Language, 7.5 years"   
local name_wj_knowas7y6m  		"WJ, Knowledge, 7.5 years"   
local name_wj_skillas7y6m  		"WJ, Skills, 7.5 years"   
local name_wj_readas8y  		"WJ, Reading, 8 years"   
local name_wj_mathas8y  		"WJ, Math, 8 years"  
local name_wj_langas8y   		"WJ, Language, 8 years" 
local name_wj_knowas8y  		"WJ, Knowledge, 8 years"  
local name_wj_skillas8y  		"WJ, Skills, 8 years"  
local name_wj_readas8y6m  		"WJ, Reading, 8.5 years"  
local name_wj_mathas8y6m   		"WJ, Math, 8.5 years"
local name_wj_langas8y6m  		"WJ, Language, 8.5 years" 
local name_wj_knowas8y6m  		"WJ, Knowledge, 8.5 years" 
local name_wj_skillas8y6m  		"WJ, Skills, 8.5 years" 
local name_wj_readas9y  		"WJ, Reading, 9 years" 
local name_wj_mathas9y  		"WJ, Math, 9 years" 
local name_wj_langas9y  		"WJ, Language, 9 years" 
local name_wj_knowas9y  		"WJ, Knowledge, 9 years" 
local name_wj_skillas9y  		"WJ, Skills, 9 years" 

local name_tot_ret 			"Number of grade retentions, 12 years"
local name_tot_sped			"Number of special ed. placements, 12 years"
local name_ever_ret 			"Ever retained, 18 years"
local name_ever_sped 			"Ever special education, 18 years"
local name_never_ret 			"Never retained, 18 years"
local name_never_sped 			"Never special education, 18 years"

local name_hs21y 			"Graduated high school, 21 years"
local name_sch_hs30y 			"Graduated high school, 30 years"
local name_years_30y 			"Years of education, 30 years"
local name_si30y_techcc_att		"Attended vocation/tech/community college, 30 years"
local name_si30y_univ_comp		"Graduated college, 30 years"
local name_hs30y 			"Graduated high school, 30 years"

local name_si30y_works_job 		"Employed, 30 years"
local name_si21y_inc_labor		"Labor income, 21 years"
local name_si30y_inc_labor 		"Labor income, 30 years"
local name_si21y_inc_trans_pub	"Public transfer income, 21 years"
local name_si30y_inc_trans_pub		"Public transfer income, 30 years"

local name_p_inc0y				"Labor income of parents, 0 years"	
local name_p_inc1y6m			"Labor income of parents, 1.5 years"
local name_p_inc2y6m			"Labor income of parents, 2.5 years"	
local name_p_inc3y6m			"Labor income of parents, 3.5 years"	
local name_p_inc4y6m			"Labor income of parents, 4.5 years"	
local name_p_inc8y				"Labor income of parents, 8 years"
local name_p_inc12y				"Labor income of parents, 12 years"
local name_p_inc15y				"Labor income of parents, 15 years"
local name_p_inc21y				"Labor income of parents, 21 years"

local name_pi_inc_trans12y		"Public transfer income, 12 years"		
local name_pi_inc_trans15y		"Public transfer income, 15 years"		
local name_m_inc_trans21y		"Mother Public transfer income, 21 years"		

local name_J_WorkWell 		"Do work well, 30 years"
local name_J_Lose 			"Don't do things that may lose job, 30 years"
local name_J_StayAway 		"Don't stay away from job, 30 years"
local name_J_Stress 		"Job not too stressful, 30 years"
local name_J_Trouble 		"No trouble finishing work, 30 years"
local name_J_Boss 			"No trouble with boss, 30 years"
local name_J_Worry 			"Not worry about work, 30 years"
local name_J_Satisfied 		"Satisfied with work, 30 years"
local name_J_Others			"Work well with others, 30 years"
	
local name_commsd 			"Job Satisfaction: Communication in organization, 30 years"
local name_coworkerssd 		"Job Satisfaction: Coworkers, 30 years"
local name_fringebensd 		"Job Satisfaction: Fringe benefits, 30 years"
local name_supervisionsd 	"Job Satisfaction: Supervisor, 30 years"
local name_natworksd 		"Job Satisfaction: Job tasks, 30 years"
local name_opprocsd			"Job Satisfaction: Operating polices/procedure, 30 years" 
local name_paysd 			"Job Satisfaction: Pay and renumeration, 30 years"
local name_promotionsd		"Job Satisfaction: Promotion opportunities, 30 years" 
local name_contrewsd		"Job Satisfaction: Recognition and awards, 30 years" 
local name_jbsttotsd		"Job Satisfaction: Total Score, 30 years"

local name_totfel 			"Number of felonies, 30 years"
local name_totmis 			"Number of misdemeanors, 30 years"
local name_ever_conv_misd		"Ever convicted of a misdemeanor, 30 years"
local name_ad34_fel 		"Total felonies (admin data), 34 years"
local name_ad34_mis 		"Total misdemeanors (admin data), 34 years" 
local name_si30y_adlt_totinc "SINT Total years incarcerated, 30 years"
local name_si30y_juv_fel "SINT Number of juvenile ($ < $16y) felony convictions, 30 years"
local name_ncharges "Youth (Admin data): Number of charges, 30 years"
local name_narrests  "Youth (Admin data): Number of arrests, 30 years"
local name_nfel  "Youth (Admin data): Number of felonies, 30 years"
local name_nmis  "Youth (Admin data): Number of misdemeanors, 30 years"
local name_nviol  "Youth (Admin data): Number of violent offenses, 30 years"
local name_nprop  "Youth (Admin data): Number of property offenses, 30 years"
local name_ndrug  "Youth (Admin data): Number of drug offenses, 30 years"
local name_nothr "Youth (Admin data): Number of other offenses, 30 years"

local name_si34y_bmi			"BMI, 34 years"
local name_si34y_obese			"Obese (BMI $ > $ 30), 34 years"
local name_si34y_diab			"Diabetes (hemoglobin $ > $ 6.5), 34 years"
local name_si34y_hemoglobin		"Hemoglobin (%), 34 years"
local name_si34y_prediab		"Prediabetes (hemoglobin $ > $ 5.7), 34 years"
local name_si34y_hyper			"Hypertension (Sys/Dia BP $ > $ 140/90), 34 years"
local name_si34y_sys_bp 		"Systolic blood pressure, 34 years"
local name_si34y_dia_bp		"Diastolic blood pressure, 34 years"
local name_si34y_prehyper 		"Prehypertensive, 34 years"
local name_si34y_drugs			"Drug user, 34 years"
local name_FRiskScore			"Framingham score, 34 years"
local name_smoker			"Ever smoked, 34 years"
