/*
Project: 	Treatment effects
Date:		April 27, 2017

This file:	Means of control group
*/

clear all
set more off

// parameters
set seed 1
global bootstraps 10
global quantiles 30

// macros
global projects		: env projects
global klmshare		: env klmshare
global klmmexico	: env klmMexico

// filepaths
global data	   	= "$klmshare/Data_Central/Abecedarian/data/ABC-CARE/extensions/cba-iv"
global scripts    	= "$projects/abccare-cba/scripts/"
global output      	= "$projects/abccare-cba/output/"

// data
cd $data
use append-abccare_iv, clear

drop if R == 0 & RV == 1

// variables
cd ${scripts}/abccare/genderdifferences
include abccare-outcomes
include abccare-reverse
include abccare-112-outcomes

foreach c in `categories' {
	if "`c'" != "all" {
		foreach v in ``c'' {
	
		
			if substr("`v'",1,6) == "factor" {
				gen `v' = .
			}
		
			forvalues s = 0/1 {
				local tofactor
				if substr("`v'",1,6) == "factor" {
					foreach v2 in ``v'' {
						sum `v2'
					gen std`v2'`s' = (`v2' - r(mean))/r(sd)
						local tofactor `tofactor' std`v2'`s'
					}
					cap factor `tofactor'
					if !_rc {
						cap predict `v'`s'
						if _rc {
							gen `v'`s' = .
						}
					}
					replace `v' = `v'`s' if male == `s'
				}
			}
		}
	}
}
	
foreach c in `categories' {
	
	// factor treatment effect
	cap factor ``c''
	if !_rc {
		cap predict factor`c' 
		if _rc {
			gen factor`c' = .
		}
	}
	else {
		gen factor`c' = .
	}
	
	forvalues s = 0/1 {
		sum factor`c' if male == `s' & R == 1
		local factor`s'`c'_R1 = r(mean)
		sum factor`c' if male == `s' & R == 0
		local factor`s'`c'_R0 = r(mean)
		
		local factor`s'`c' = `factor`s'`c'_R1' - `factor`s'`c'_R0'
		local factor`s'`c' = round(`factor`s'`c'', 0.001)
	}
	
	// average treatment effect
	foreach v in ``c'' {
		
		if "`c'" != "all" {
			qui sum `v' 
			replace `v' = (`v' - r(mean) ) / r(sd)
		
		
			forvalues s = 0/1 {
		
				qui sum `v' if male == `s' & R == 0  //& dc_mo_pre == 0 //dc_mo_pre > 0 & dc_mo_pre != . //
				local b`v'`s'`b'_R0 = r(mean)
				qui sum `v' if male == `s' & R == 1
				local b`v'`s'`b'_R1 = r(mean)
				
				// calculate treatment effect and store by category
				matrix te`s'_`c' = (nullmat(te`s'_`c') \ `b`v'1`b'_R1' - `b`v'0`b'_R0')
				matrix te`s'_all = (nullmat(te`s'_all) \ `b`v'1`b'_R1' - `b`v'0`b'_R0')
			}
		}
		
		forvalues s = 0/1 {
			mat ones`s'_`c' = J(rowsof(te`s'_`c'),1,1)
			mat sum`s'_`c' = ones`s'_`c''*te`s'_`c'
			mat avg`s'_`c' = sum`s'_`c'/rowsof(te`s'_`c')
			mat list avg`s'_`c'
			local avg`s'_`c' = avg`s'_`c'[1,1]
			local avg`s'_`c' = round(`avg`s'_`c'', 0.001)
		}
	}
}

file open tabfile using "${output}/abccare-category-tes.tex", replace write
file write tabfile "\begin{tabular}{l c c c}" _n
file write tabfile "\toprule" _n
file write tabfile "Category & \# Outcomes & \mc{2}{c}{Mean Treatment Effect}  \\" _n
file write tabfile "\cmidrule(lr){3-4}" _n
file write tabfile "		&	&  Female & Male  \\" _n
file write tabfile "\midrule" _n	

foreach c in `categories' {
	local `c'_N : word count ``c''
	
	if "`c'" == "all" {
		file write tabfile "\midrule" _n
	}
	file write tabfile "``c'_name' & $ ``c'_N' $ & $ `avg0_`c'' $ & $ `avg1_`c'' $ \\" _n
}

file write tabfile "\bottomrule" _n
file write tabfile "\end{tabular}" _n
file write tabfile "% This file generated by: abccare-cba/scripts/abccare/genderdifferences/abccare-category-tes.do" _n
file close tabfile
